saadeghi/daisyui

colors/color-values.js, colors/index.js, colors/windi.js
Support WindiCSS color format in tailwind.config.js.  Non-breaking change.
- Moves the colors.js file into /colors/index.
- Moves the colorValues variable into its own file.
- Creates a new `colors/windi.js` file, which allows user to `require(‘daisyui/colors/windi’)`
Hi, @saadeghi!  I really appreciate your work with DaisyUI.  Actually, I appreciate it so much that I spent the day figuring out how to get it to work with WindiCSS (https://windicss.org/).  WindiCSS is the TailwindCSS compiler that inspired creation of the new TailwindJIT compiler that was announced in the last week or so.  The competition has definitely been supportive for the Tailwind community, and now we have options.
Tailwind and Windi support the same classes and utilities, but their plugin APIs are different.
- The …
=> feat: Add support for WindiCSS

src/docs/pages/components/badge.vue
Fix typo in the docs for the badge component in the docs (Badg -> Badge)
=> fix(Docs/components/Badge): Fix typo in the docs for the badge component

.gitignore, src/docs/pages/core/colors.vue
`<input type="color"...` doesn't allow hex color value to be pasted in, it's too complicated to use. This change allows us to make it simpler
=> Site: Allow to directly enter color hex

src/docs/pages/components/table.vue
=> Fixed typo in table documentation

src/components/styled/breadcrumbs.css
As shown, the breadcrumb separator is overlaid with a global style, so I set the background of the separator to a transparent color.
=> fix(breadcrumbs): Remove the breadcrumb separator background color

src/components/unstyled/toggle.css
I added the flex-shrink property to the unstyled toggle class to prevent the toggle from shrinking in a flex container.
=> fix: #394 prevent toggle from shrinking by default

src/components/styled/select.css
Hi Pouya,
When the <select> element multiple attribute is active, I notice the triangle icons are shown, but in this situation it's not useful, so I removed it.
=> Removes the triangle icon in multiple select

src/components/styled/select.css
Removes the triangle icon in select when the size attribute is used and the size is not equal to one
=> Removes the triangle in select (size attribute)

src/components/unstyled/checkbox.css
This fixes the issue of checkboxes shrinking in flex and grid containers by default. I added the flex-shrink property to the checkbox class with a value of 0.
=> fix: #428 checkbox input shrink property.

src/docs/src/routes/components/artboard.svelte.md
First six demo sections were all titled "Artboard size 6". Updated to match the actual size in each section.
=> fix(docs) duplicated names for demo sections in Artboard

src/docs/src/routes/components/input.svelte.md
tiny typo at https://daisyui.com/components/input/.
Preview and html texts are not same. 
"What is your name?"
"Your email address"
Changed html label-text ("Your email address") to "What is your name?".
=> fix a very tiny typo at Text Input

src/docs/src/translation/jp.json
idk but `<br />` appeared
If you know the solution to fix this, please fix it.
=>  fix <br />

src/docs/src/routes/docs/themes.svelte.md
Update theme docs:
`cmyk` can be applied on any HTML tag with `data-theme='cupcake'`
to
`cmyk` can be applied on any HTML tag with `data-theme='cmyk'`
=> fix: Change `cupcake` for `cmyk`

src/docs/src/routes/components/input.svelte.md, src/docs/src/routes/components/select.svelte.md, src/docs/src/routes/components/textarea.svelte.md
In the documentation, all the descriptions of the ghost variant referred to the checkbox ("_Adds ghost style to checkbox"_).
To be more precise, it appeared in:
- [Text input](https://daisyui.com/components/input/);
- [Select](https://daisyui.com/components/select/);
- [Textarea](https://daisyui.com/components/textarea/);
=> docs: ghost form elements' descriptions always refer to checkbox

src/docs/src/routes/components/collapse.svelte.md
Changing the text inside the collapse modifies the width of the containers in the docs to not line up - see below.
If that's a problem could set a fixed width for them all?
=> fix: tabindex=0 breaks collapse with checkbox on safari

src/colors/themes.js
There is a duplicate `--rounded-btn` in Pastel theme.
=> fix: duplicate theme color

src/docs/src/routes/components/drawer.svelte.md, src/docs/src/routes/components/modal.svelte.md
hopefully this regex catches everything
- find: `label for="([\w-]+)" className`
- replace: `label htmlFor="$1" className`
=> fix: corrected incorrect jsx attribute on drawer and modal components

src/docs/src/routes/components/navbar.svelte.md
Fix missspelling of strokeLinecap in Navbar example in the docs
=> Fix: strokeLineCap in navbar example

src/docs/src/routes/components/card.svelte.md
`img` tag inside `<figure><figure/>` closed with a **/**
=> docs: fixed typo in components/card issue #1122

src/docs/src/components/ClassTable.svelte, src/docs/src/translation/en.json, src/docs/src/translation/es.json, src/docs/src/translation/fr.json, src/docs/src/translation/id.json, src/docs/src/translation/jp.json, src/docs/src/translation/ko.json, src/docs/src/translation/pt.json, src/docs/src/translation/ru.json, src/docs/src/translation/zh_cn.json, src/docs/src/translation/zh_tw.json
Prefix reference link was changed from `/docs/config/` to `/docs/config/#prefix`
=> Docs: Update prefix reference link in ClassTable

src/docs/src/routes/components/hero.svelte.md
Correct typo in `components/hero`:
`Overlay the covers the background image` -> `Overlay that covers the background image`
=> Docs: Correct typo in components/hero

src/utilities/styled/button.css
Currently, if you have buttons of different types (`a` vs `button` for example), the button styling breaks because the selectors depend on the button type:
Change to using child selectors as this doesn't care what type of child exists.
Note I haven't directly tested this change against DaisyUI's demos, etc, instead I applied these styles locally to verify:
```css
.btn-group .btn {
@apply rounded-none;
&:first-child {
@apply rounded-l-lg;
}
&:last-child {
@apply rounded-r-lg;
}
}
```
PS any reason not to use `@apply` in the code?
=> Fix border radius on mixed type buttons

src/docs/src/routes/components/stat.svelte.md
`stat-actions` was missing in the table, but used in an example below
=> Update stat doc to mention `stat-actions`

src/components/styled/dropdown.css, src/components/styled/tooltip.css, src/components/unstyled/dropdown.css, src/components/unstyled/tooltip.css, src/docs/src/routes/components/dropdown.svelte.md, src/docs/src/routes/components/tooltip.svelte.md
This PR adds the `dropdown-bottom` and `tooltip-top` modifiers. They are needed for the following use case:
* Show dropdown on top on mobile and on bottom on desktop. It's impossible without the `dropdown-bottom` modifier, since the `dropdown-top` would be applied for all screen sizes and there would be no class to override it. e.g.
```html
<div class="dropdown dropdown-top lg:dropdown-bottom">
```
The same use case applies to the tooltip, but the bottom and top are inverted. e.g.
```html
<div class="tooltip tooltip-bottom lg:tooltip-top">
```
https://user-images.githubusercontent.com/5948318/194936865-8fabeff4-90da-4fbf-88c1-d18822af7341.mov
=> fix: #1218 - Add missing modifiers on dropdown and tooltip

src/docs/src/routes/components/bottom-navigation.svelte.md, src/docs/src/routes/components/countdown.svelte.md, src/docs/src/routes/docs/config.svelte.md, src/docs/src/routes/docs/customize.svelte.md, src/docs/src/routes/docs/layout-and-typography.svelte.md
- Added missing periods
- Minor changes to fix punctuation + grammar
=> fix(docs): missing periods + minor changes

src/components/unstyled/collapse.css
In a personal project I have a collapsed list that exceeds `9000px` when opened. As far as I understand it this value is a probably-big-enough value to offset the `max-height: 0` when the collapse is closed. Since the CSS selector is more specific `max-height: none` in the `collapse-content` should also create the same behaviour while allowing for any height.
Let me know if I'm missing something.
=> fix: remove collapse-content cutoff

src/components/styled/file-input.css
This adds `rounded-btn` to the file-selector-button pseudo element that Safari renders the file input button as. Closes #1350
=> fix: #1350 File Input Button for Safari

src/docs/src/routes/components/menu.svelte.md
As you can see in https://daisyui.com/components/menu/#item-with-border, the item that is meant to have a border, does not.
=> fix(docs): Bordered menu item preview has incorrect class

src/components/unstyled/input.css, src/components/unstyled/textarea.css, src/docs/src/routes/components/textarea.svelte.md, src/utilities/unstyled/textarea.css
=> textarea-<size>

src/docs/src/routes/components/chat.svelte.md
The text in the description should be `primary` instead of `secondary`
=> Fix small error in the description

src/components/styled/checkbox.css, src/components/styled/radio.css, src/components/styled/toggle.css
The word `compatibility` is misspelled in various components.
=> Fix small typo in css comments

src/components/styled/tab.css
Hello! I made a very simple and straightforward modification to fix a bug that I found in a project of mine.
**Description of the problem**: In the layout [Boxed Tabs](https://daisyui.com/components/tab/#boxed), the tabs had `border-radius` set only when _active_ (with the attribute `tab-active`).
The implications of such behavior are evident if, for instance, we set a different `background-color` for the other elements:
Such behavior is also quite annoying while working with transitions or other kind of animations.
**The solution**: The easy and clean solution is simply to apply the `border-radius` to all the `.tab` elements. Even if they are transparent, they will have the property set and they will behave accordingly even when colored or animated.
Thank you very much for such a great …
=> fix: border-radius in now applied to all tabs, whether active or not (in tabs-boxed layout)

src/docs/src/routes/components/card.svelte.md
The code examples in the docs weren't using the reactive prefix for the `image-full` modifier.
This fixes the issue.
=> Fix `image-full` modifier to use the correct prefix in the card component

src/components/styled/menu.css
When there's an only child, both the `:first-child` and `:last-child` selectors match on the same element. Because of how CSS manages conflicting rules, the latter rule overrides the former, resulting in the top-left and top-right border radius getting unset.
I've added two rules for the menu and two more for the submenu in order to handle this specific case, targeting a child which is both first and last child. If that is the case we want all four corners to be set on `border-radius: inherit`.
=> fix: #778 fixed border radius of menu and submenu with only child

src/components/styled/radio.css
the transition of radio component doesn't work well at Safari.
https://user-images.githubusercontent.com/62830430/234827331-4ac1ad69-a0ad-49d9-84b2-12905740b53d.mov
removing this transition doesn't change any animation effect of radio.
=> fix: safari radio component transition

src/components/styled/table.css
So the table uses the normal tailwind classes
```
@apply rounded-tl-lg;
@apply rounded-tr-lg;
@apply rounded-bl-lg;
@apply rounded-br-lg;
```
this  dosnt match with themes that dont have border radius
so i made that they use the daisyui -box modifier
```
@apply rounded-tl-box;
@apply rounded-tr-box;
@apply rounded-bl-box;
@apply rounded-br-box;
```
now the table border radius match with the theme config
=> feat: use for border radius -box instead of -xl so they can match with theme configuration

src/utilities/styled/button.css
This PR fixes the button group border-radius issue on the right-to-left pages.
Before:
After:
=> fix: btn-group right-to-left direction border radius

src/components/unstyled/tooltip.css
Fixes bug: tooltip z-index should be greater than `<th>` element #1798
Fixes #1798
=> fix: tooltip z-index

src/docs/src/routes/components/navbar/+page.svelte.md
While testing JSX sample for "Navbar with menu and submenu".. with Qwik, saw error for `<details>` tag not closing properly.
The sample code had a slight mis-order 
```
<li>
<details>
...
</li>
</details>
```
bringing closing `</details>` tag under `<li/>` fixes the run issue & is the correct nesting anyway.
=> Fix doc's jsx sample for navbar menu with submenu

src/docs/src/routes/components/navbar/+page.svelte.md
Make `<details>` tags close in the correct order and not straddle `<li>` tags, and also make the indentation standard to match the other examples.
=> Navbar example closes details tag in the wrong order

src/docs/src/routes/components/join/+page.svelte.md
- `Custom broder radius` should be `Custom border radius`
- Uppercased the first letter of some text, such as `item inside join.` and `group items vertically`
=> Fix typo, apply text consistency

src/docs/src/routes/+page.svelte
Fixes "Get Started" button alignment in the homepage when breakpoint is md or lg.
<details>
<summary>Current behaviour:</summary>
</details>
<details>
<summary>Fixed behaviour:</summary>
</details>
Other breakpoints remain unchanged:
<details>
<summary>Up to sm:</summary>
</details>
<details>
<summary>Xl onwards:</summary>
</details>
=> fix(homepage): center get started button on md and lg

src/docs/src/routes/components/modal/+page.svelte.md
It has probably been a typo, but "for" property is not applicable to the button element.
=> fix: remove the invalid "for" property from the close button

src/docs/src/routes/components/join/+page.svelte.md
In the [docs](https://daisyui.com/components/join/#group-items-vertically) at `Group items vertically` there is a typo. This fixes the typo.
=> Add missing `$` to `Join` docs

src/components/unstyled/drawer.css
Fixes bug #1888, `drawer-overlay`'s dimensions no longer collapse and `drawer-side` no longer disappears when the drawer is closed.
https://github.com/saadeghi/daisyui/assets/54014569/c285ba58-effe-44f5-9dbf-062f85c086ec
=> fix: #1888 drawer now animates out

src/components/unstyled/collapse.css, src/docs/src/routes/components/collapse/+page.svelte.md
Added animations and fixed the border radius bug on the collapse component when it closes. I also changed [this part of the documentation for collapse](https://daisyui.com/components/collapse/#custom-colors-for-collapse-that-works-with-checkbox) to use `peer-checked` like it suggests in the info box above the code box.
Example of new behavior:
https://github.com/saadeghi/daisyui/assets/54014569/7a1e96a4-920f-40d0-873d-746a7501c729
=> fix #1992: add/fix anims and improve docs for collapse

README.md, src/components/styled/mockup.css, src/components/unstyled/mockup.css, src/docs/src/lib/data.js, src/docs/src/routes/components/mockup-browser/+page.svelte.md
Added the browser component that I saw in [README list](https://github.com/saadeghi/daisyui#-list-of-components), I made this mockup responsive and simple as possible.
=> feat: add the browser mockup component from README.md list

src/docs/src/translation/pt.json
In this pull request, I made a correction to the title of the home page to improve verb agreement. I changed "O mais popular biblioteca de componentes" to "A mais popular biblioteca de componentes". This adjustment ensures that the adjective "popular" agrees correctly with the feminine singular noun "biblioteca" in the Portuguese language.
In the Portuguese language, noun-adjective agreement is an essential grammatical feature. Adjectives must agree in gender (masculine or feminine) and number (singular or plural) with the nouns they modify. This agreement helps to maintain clarity and precision in communication, as it ensures that adjectives match the gender and number of the nouns they refer to.
=> docs: typo correction in the src/docs/src/translation/pt.json

src/index.d.ts
Added types for configuration.
Further steps after this got merged:
- Add types for the exported themes
- Add the config to the tailwind config
I have attempted both of these with no luck so far:
```ts
// tw module augmentation
declare module 'tailwindcss' {
type Config = {
daisyui?: DaisyUIConfig;
}
}
// themes export shim
declare module 'daisyui/src/theming/themes' {
declare const themes: CustomTheme;
export default themes;
}
```
=> Added configuration types

src/components/unstyled/join.css
This closes #2333.
Here's a how it looks like
for reference, this is how it used to be:
=> fix: #2333 multidirection support for `join`

src/docs/src/routes/(docs)/components/radial-progress/+page.svelte.md
I reviewed #2472 and have tried to consider the discussion there in the changes made. 
**Changes**
This PR adds an explicit role of 'progressbar' to all JSX and HTML examples.
There is already an alert calling out the fact that the standard progress bar uses a `<progress>` element while the radial progress bar uses a `<div>` to work around browser-side issues, this has been expanded to explain that `<progress>` receives it's role implicitly so when using a `<div>` instead we need to add this role explicitly.
**Rationale**
This is not an exhaustive list of the boxes that I would want to see checked from an accessibility perspective, but as mentioned in referenced issue and in Twitter discussion, because Daisy is pure-CSS, there are some things that cannot be demonstrated effectively …
=> Docs: Accessibility Note on Radial Progress Bar

src/docs/src/routes/(docs)/docs/config/+page.svelte.md, src/theming/functions.js
If variables are attached to `:root`, they don't seem to correctly transcend a shadow root's boundaries. I hacked my local daisyUI installation to attach the variables to `*` (like Tailwind itself does), and that makes the variables accessible for all elements.
=> Add themeSelector for shadow root use cases

src/components/styled/select.css
Issue: css selector can't find the select element.
Related issue tickets: 
* https://github.com/saadeghi/daisyui/issues/2505 
* https://github.com/saadeghi/daisyui/issues/2513
See example in docs: https://daisyui.com/components/select/
Before PR:
After PR:
=> fix: #2505 missing border on select component

src/docs/src/lib/data/roadmap.js
I went to the roadmap and found that under 'Upcoming,' the 'New Component: Banner' shows up twice.
=> "New component: Banner" showing up twice in Upcoming Roadmap

src/theming/functions.js
Hey!
Again, great release!
Since we're using the DaisyUI's custom theme generator in our application, performance really matters to us
After a first look, I see that `toGamut` function is always constructed with oklch, so we can extract it to make it a lot faster as V8 will now be able to optimize it, same goes with `cut`
Hope to create more PRs improving performance soon 🙏
=> perf: cache functions that get called frequently

src/theming/functions.js
We can use hasOwn here as it's safer and [is intended as the modern replacement to `hasOwnProperty`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)
=> Prefer hasOwn

src/docs/src/routes/(docs)/components/footer/+page.svelte.md
As @bempensato mentioned in #2294 (and reported in #2789), having a `<header>` as a child of `<footer>` is invalid.
Moving to use an `<h6>` tag as it has the lowest weight of a page's heading tags and still properly represents a heading of the `<nav>` section.
Ran through the W3C validator to confirm, passes with flying colors:
Note I also changed `<br/>` to `<br>` as the validator warns the trailing slash is unnecessary.
Closes #2789
=> Use h6 instead of header in footer component examples

src/docs/src/routes/(docs)/components/accordion/+page.svelte.md
Fixed an issue with the example code for accordion.
The flawed code:
- Rendered a read-only field due to checked being set to a value instead of using "defaultChecked".
- Raised an error in TypeScript (TS2322: Type `string` is not assignable to type `boolean | undefined`)
This addresses both those issues
=> Fixed flawed example code for Accordion

src/components/unstyled/carousel.css, src/docs/src/routes/(docs)/components/carousel/+page.svelte.md
If we add `carousel-center` to the classname for mobile devices and it'd be hard to change it back to the default `scroll-snap-align: start` behaviour for desktop. So just add this `carousel-start` modifier and use `lg:carousel-start` for this senario.
=> Add carousel-start modifier

src/docs/src/routes/(docs)/components/theme-controller/+page.svelte.md
makes the hover state consistent on all of the theme controller and allows for clicking on the icons.
https://daisyui.com/components/theme-controller/
-> Clickthough suprisingly works on the daisyui website for me, but the hoverstate not
=> fix: clickthrough on theme controller with icons on the website

src/docs/src/routes/(docs)/components/stat/+page.svelte.md
Changed "deposit" to "Deposit" to maintain consistent capitalization as I believe it makes the docs more consistent both aesthetically and in logic.
Feel free to disregard if not needed!
=> [DOC SITE] Small change to capitalization in final stat component example

src/components/styled/tab.css, src/components/unstyled/tab.css
Supplement the `.tab-active` modifier to also support elements rendered with `[aria-selected="true"]`. When an element with `[role="tab"]` nested within a `[role="tablist"]` becomes "active" or "selected", its `[aria-selected]` attribute must be set to `"true"`. Similarly, when a tab is inactive, its `[aria-selected]` must be removed or set to `"false"` (according to the [WAI ARIA Guidelines][]).
Since all compliant tab implementations must set this attribute, and *not all* compliant tab implementations provide hooks to configure CSS Class List changes to be made alongside those attribute changes, this commit modifies the `tab.css` files to target either `.tab-active` or `[aria-selected="true"]` using the CSS [:is][] psuedo-class.
[WAI ARIA Guidelines]: …
=> Supplement `.tab-active` modifier

src/utilities/styled/tooltip.css
If a parent of tooltips has no-wrap or truncate, the tooltip text will overflow if it exceeds the max-width. Adding whitespace-normal to tooltip:before will reset this behavior.
=> Tooltip max-width whitespace wrapping

src/docs/src/routes/(redirects)/tailwindplay/+page.server.js
Update an image extension at chat bubble avatar on tailwindplay.
The [present tailwindplay](https://play.tailwindcss.com/IvZT5sJSsa) uses [jpg image](https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg) at avatar.
However, jpg image doesn't load anymore.
Then I recreate [new tailwindplay link](https://play.tailwindcss.com/wWndQ9FxeZ) (https://play.tailwindcss.com/wWndQ9FxeZ) which has webp image.
It shows a women face correctly.
=> docs: use webp image on tailwindplay

src/components/styled/stat.css
I recently noticed performance issues caused by a single selector in `src/components/styled/stat.css`:
```
:is([dir="rtl"] .stats > :not([hidden]) ~ :not([hidden])) {
--tw-divide-x-reverse: 1;
}
```
It is taking a significant % of the total time in the Recalculate Style step (dev tools performance) with 0 matching elements. Also, my site is not `rtl` so I believe it shouldn't be trying to apply those styles. Here's a table showing the timings
| Recalculation | Total | Selector |
|--------|--------|--------|
| 1 | 139ms | 115ms |
| 2 | 107ms | 94ms |
| 3 | 112ms | 96ms |
| 4 | 119ms | 97ms |
| 5 | 117ms | 97ms | 
So on average, it takes 84% of the total recalculation and with 5 recalculations on the first page load my page is getting hit with an extra 500ms delay.
I've rewritten it, and it …
=> Rewrite selector causing performance issues

src/components/unstyled/drawer.css
Fixes #3249
This is not a bug that happens when you only have a single drawer on the page. But when you have 2 drawers nested, and the outer drawer was a `drawer-end` variant, then both drawer toggles would open the end drawer.
Here's a comparison of what happened before and after
__Before__
https://github.com/user-attachments/assets/8d228aa0-568c-4e4b-a551-4fd450eded9f
__After__
https://github.com/user-attachments/assets/b7f274cd-0802-48b0-ac00-9ef6aacee528
=> Fix `.drawer-end` nesting

src/components/styled/collapse.css, src/components/unstyled/collapse.css
Closes: https://github.com/saadeghi/daisyui/issues/3268
Specifying width and height for collapse input to make sure it is taking up all space in grid using any browsers.
=> fix: #3268 unstyled collapse input size

src/components/unstyled/collapse.css
When toggling show/hide, if the title has a different background color than the content, and if there is lengthy content, you can see the title row/track grow during the animation before returning to its original size. Using `max-content` instead of `auto` in the grid-template-rows rules should lock the height of the title, so only the 2nd row (content) changes from `0fr` to `1fr`.
Original issue:
https://github.com/user-attachments/assets/a56c62ec-7ed7-4dfe-ab03-6ad1bdec2bcb
With the style change in this pull request:
https://github.com/user-attachments/assets/def5447c-3d69-40e2-a15e-c31fe6bc0a4c
Thanks for considering, love the component library!
=> Prevent height change in Collapse component title

packages/docs/src/components/themegenerator/PreviewGrid.svelte
Minor class misplacement issue 
```
<div class='text-xl' font-semibold>Daisy grows happily under the warm sunlight</div>
```
=> fix(docs):  Move 'font-semibold' inside the class attribute

packages/docs/src/routes/(routes)/docs/install/rails/+page.md
4.0.0 got released a few days ago: https://github.com/rails/tailwindcss-rails/releases/tag/v4.0.0
=> Use releases 4.0.0 version in Rails guide

packages/docs/src/routes/(routes)/docs/themes/+page.md
Removed unnecessary colons after class names in the example code, which were causing syntax errors.
=> Corrected example code by removing incorrect colons

packages/docs/src/routes/(routes)/components/tab/+page.md
Removed the role="tab" attribute from the input element due to a Google Lighthouse warning about using ARIA roles incorrectly. This role was unnecessary and could negatively affect accessibility scores. The removal is not expected to impact functionality.
=> Removed roles from input elements for cccessibility compliance

packages/docs/src/routes/(routes)/docs/themes/+page.md
The example now shows how to use the new custom theme (add it to the themes list in the daisyui plugin configuration) and enables it (default: true).
=> Update custom theme documentation

packages/docs/src/routes/(routes)/components/join/+page.md
Remove `input-bordered` and `select-bordered` classes  (not needed anymore).
=> docs: remove unnecessary classes

packages/daisyui/src/components/loading.css
For the default size, the width is defined using the Tailwind CSS `w-6` class. However, for other sizes, including `md`, the width is specified using a CSS variable.
**Changes:**
- Removed `w-6` (fixed width class).
- Added width: calc(var(--size-selector, 0.25rem) * 6); for dynamic sizing.
**Reason for Change:**
- Enables customization of the width based on `--size-selector`, improving responsiveness and adaptability.
Let me know if you’d like any refinements!
=> V5: Fixed loading component default size

CHANGELOG.md
Typo error for mockup class in changelog.
Please refer to the attached screenshot:
=> Docs: class typo for mockup in changelog

packages/docs/src/routes/(routes)/docs/install/wordpress/+page.md
Until this PR https://github.com/esm-dev/esm.sh/pull/1077 got deployed on the esm.sh, we are using the jsDelivr CDN.
=> v5 (Docs): Updated WordPress installation guide

packages/daisyui/src/components/collapse.css
In v4, using `collapse-open` would rotate a collapse arrow.
Currently with v5 beta, this is not the case and only the attribute `open` allows to rotate the arrow (+ input checkbox, focus and so on).
This PR proposes to align the behavior with daisyui v4.
=> fix(collapse): collapse arrow not rotated when using collapse-open

.gitignore
Bun v1.2 changed the default lockfile format to the text-based `bun.lock`.
[Source](https://bun.sh/docs/install/lockfile)
=> Add "bun.lock" to .gitignore

packages/daisyui/functions/getFileNames.js
This fixes an issue where the recursive call to `getFileNames` mistakenly passed `recursive` instead of `extension`. 
Now, the function correctly uses the `extension` parameter in recursive calls.
This PR is targeted for the `v5` branch.
=> fix(getFileNames): Fix the recursive call to add the extension

packages/daisyui/src/components/button.css
When a checkbox or radio is checked and styled as btn-outline with btn-[color], the text color does not display correctly.
Before
After
=> fix(button.css): update btn-outline styles to include checked state

packages/docs/src/routes/(routes)/components/button/+page.md
Removed the extra shown disabled button with btn-outline instead of adding it to the shown HTML, as btn-outline does not change how the disabled button looks.
=> Docs: Fix disabled button HTML differing from preview.

CHANGELOG.md
Some of the more recent CHANGELOG updates didn't properly link to the issues they fixed.
Fixes #3694
=> Linkify CHANGELOG issues

packages/docs/src/routes/(routes)/components/theme-controller/+page.md
Fix element 'input' has no corresponding closing tag at section [Theme Controller using a toggle with icons inside](https://daisyui.com/components/theme-controller/#theme-controller-using-a-toggle-with-icons-inside).
=> docs: fix self-closing tag for input

packages/docs/src/components/SEO.svelte
Fixed the image URL generation logic for `og:image` and `twitter:image` tags in the documentation site's SEO component.
Removed the call to `readEnv("VITE_ROOT")` because the value of `$props().img` is always passed as an absolute path URL.
=> fix(docs/seo): Remove VITE_ROOT prefix from SEO image paths

packages/daisyui/src/components/input.css
I noticed that this component was using the inline-block utility but had been changed to inline-flex to address an issue in Safari.
I decided to keep inline-flex as the default and revert only the date input back to inline-block.
Let me know if you need any adjustments!
=> fix: #3708 input type date inside input class on chromium-based

packages/daisyui/src/components/collapse.css
After the update to latest version, still one of the line has a typo that I changed with this PR + an additional duplicate key
=> fix: collapse-content transition duplicate, transition typo

packages/daisyui/src/components/validator.css
This change would allow users to set their own validator states not based on native HTML validation (which can be limited), while not adding any additional classes.
It also encourages using the existing `aria-invalid` property, increasing accessibility.
=> Add `aria-invalid` to the validator error selectors

packages/daisyui/src/components/tooltip.css
Fixes #3819
When a tooltip has an empty data-tip attribute or empty tooltip-content, it still shows a small artifact on hover. This looks like a UI bug.
I added CSS rules to hide the tooltip when:
- data-tip attribute is missing
- data-tip attribute is empty
- tooltip-content is empty
- tooltip-content only has empty children
Now empty tooltips don't show up at all, which is what users would expect.
I tested this with examples from the issue:
- Tooltip with empty data-tip=""
- Tooltip with empty tooltip-content
Before: Empty tooltips showed a strange artifact
After: Empty tooltips stay completely hidden
=> fix: tooltip showing when data-tip or tooltip-content is empty. closes: #3819

packages/daisyui/src/components/button.css
Fixes #3817 
On mobile devices (iOS Safari and others), when you tap soft, outline, or dash buttons, they get stuck in hover state. The button stays colored until you tap somewhere else on the screen.
I added CSS that targets touch devices (using `hover: none` media query) to fix the three button types:
- soft buttons
- outline buttons
- dash buttons
Now the buttons go back to normal right after you tap them.
I tested this on iPhone with Safari and with Chrome's mobile screen mode.
=> fix: button hover state persisting on mobile screen. closes: #3817

packages/docs/src/routes/(routes)/docs/editor/grok/+page.md
Hello,
This PR mention the possibility to use the doc for LLM through grok workspace instead of deepsearch. This is what I do and it works well. This make the process easier as there's no need to copy a link everytime, and much faster as deepsearch is not needed, for very similar result.
As this is a minor PR, I did not create an issue. I can totally do it if you prefer. 
Also I had trouble building the website. Here's the error I encountered with bun
```
$ : bun run build
$ NODE_ENV=production vite build --logLevel error
✗ Build failed in 3.96s
error during build:
[vite]: Rollup failed to resolve import "daisyui/theme/object" from "/home/noah/Documents/daisyui/packages/docs/src/routes/(routes)/theme-generator/+page.server.js".
This is most likely unintended because it can break your …
```
=> docs: mention workspace attachment in grok doc

packages/daisyui/src/components/collapse.css
Fixes #3885 
I believe the `3.75rem` min-height was set for safety reasons. However, this makes it impractical to use smaller font sizes, such as the default `text-xs`, and requires strong overrides.
The `1lh` value is supported by all browsers targeted as the minimum by TailwindCSS v4. Since DaisyUI also relies on TailwindCSS v4, I believe using `1lh` is justified. Moreover, if it's not supported, the fallback value of `3.75rem` still works well.
=> fix(collapse): min-height 1lh if supported

packages/daisyui/src/components/button.css
Fixes #3888
Link and ghost buttons remain "stuck" in hover state after being touched on mobile devices until users tap elsewhere. Similar to issue #3817 that was fixed for other button types in PR #3820.
Added proper @media (hover: none) queries for both button types to reset hover styles on touch devices:
- For link buttons: Applied no-underline on hover
- For ghost buttons: Reset background, border and shadow properties
Verified on iOS Safari and Chrome mobile that buttons no longer maintain hover states after being tapped.
=> fix: button link and ghost hover states persisting on mobile devices. closes: #3888

packages/daisyui/src/components/input.css
Fixes #3886
URL and email inputs with icons don't maintain their LTR direction when used in RTL contexts. Since URLs and email addresses are universally written with Latin characters, they should always be displayed left-to-right, regardless of the page's text direction.
Added a CSS rule that explicitly sets `direction: ltr;` for URL and email input types.
Tested with URL and email inputs with icons on the daisyUI demo site with Arabic language (RTL) enabled, confirming correct left-to-right text direction and proper icon placement.
=> fix: URL and email inputs maintain LTR direction in RTL context. closes: #3886

packages/daisyui/src/utilities/join.css
Fixes #3877
Disabled buttons in join components don't maintain consistent border styling because they're excluded from receiving the negative margins applied to regular buttons.
Removed the disabled button exclusions (`:disabled`, `[disabled]`, `.btn-disabled`) from the CSS selector in join.css so all buttons receive the same negative margin treatment.
Tested with various join component configurations including both enabled and disabled buttons.
=> fix: disabled button border inconsistency in join component. closes: #3877

packages/daisyui/src/components/indicator.css
Fixes #3905
The indicator component has consistent spelling typos in CSS variable names throughout the file - "inidicator" instead of "indicator". While this doesn't break functionality since the spelling is consistent, it affects code quality and readability.
Corrected all CSS variable names from "inidicator" to "indicator":
- `--inidicator-t` → `--indicator-t`
- `--inidicator-b` → `--indicator-b` 
- `--inidicator-s` → `--indicator-s`
- `--inidicator-e` → `--indicator-e`
- `--inidicator-x` → `--indicator-x`
Updated all references across indicator positioning classes (start, center, end, top, middle, bottom).
Tested indicator component positioning in Chrome and Safari. All positioning variants work correctly with the corrected variable names.
=> fix: correct spelling typos in indicator CSS variables. closes: #3905

packages/daisyui/functions/variables.css
Fixes #3909
CSS syntax error in variables.css uses commas instead of semicolons.
Corrected CSS property syntax in `packages/daisyui/functions/variables.css`:
- `--size-selector: ,` → `--size-selector: ;`
- `--size-field: ,` → `--size-field: ;`
No tests required
=> fix: correct CSS syntax error in variables.css. closes: #3909

packages/daisyui/src/components/checkbox.css
Fixes #3979
Indeterminate checkboxes with color variants (checkbox-primary, checkbox-secondary, etc.) have nearly invisible dash marks due to poor contrast. The issue occurs when color content is similar to the background, making the dash blend invisibly.
Additionally, the codebase has an inconsistency where borders use semantic fallbacks (`color-mix(in oklab, var(--color-base-content) 20%, #0000)`) but the checked state uses a hardcoded `#0000` fallback.
Applied a solution using semantic fallbacks consistent with daisyUI's established patterns:
**1. Updated checked state background-color:**
```css
// Before
background-color: var(--input-color, #0000);
// After  
background-color: var(--input-color, color-mix(in oklab, var(--color-base-content) 20%, #0000));
```
**2. Added indeterminate …
=> fix: use semantic fallbacks for checkbox states, improve indeterminate visibility. closes: #3979

packages/daisyui/src/components/calendar.css
Fixes #4042
Hovering over selected dates in cally calendars makes text hard to read due to poor contrast
Selected dates have light text (var(--color-base-100)) that becomes unreadable when the hover state applies a light background (var(--color-base-200)).
Added specific CSS rule for selected dates on hover that changes text color to var(--color-base-content) while keeping the var(--color-base-200) background
Tested in playground with both single date and date range calendars
=> fix: improve text contrast for selected cally dates on hover closes: #4042

packages/docs/src/routes/(routes)/components/filter/+page.md
Introduces a new filter example using checkboxes in addition to the existing radio button example.  
- Demonstrates filtering with multiple selections (without `filter` class)
- Keeps the reset button for clearing all selections
=> Add checkbox filter example with multi-selection

packages/daisyui/src/components/carousel.css, packages/daisyui/src/components/collapse.css, packages/daisyui/src/components/dropdown.css, packages/daisyui/src/components/progress.css, packages/daisyui/src/components/radio.css, packages/daisyui/src/components/rating.css, packages/daisyui/src/components/skeleton.css, packages/daisyui/src/components/swap.css, packages/daisyui/src/components/toast.css, packages/daisyui/src/components/tooltip.css
Disable animations when users prefer reduced motion:
- skeleton: remove shimmer animation
- progress: use solid fill instead of moving stripes
- collapse: disable grid transitions and rotations
- toast, dropdown, rating, radio: disable entry animations
- swap, tooltip: disable transform transitions
- carousel: disable smooth scroll (already implemented)
Improves accessibility for users with vestibular disorders
NOTE: I wasn't able to test this because the current animations
makes me feel sick, so I was making these changes just by
code inspection.
=> feat(a11y): add prefers-reduced-motion support

packages/daisyui/src/components/modal.css
Fixes #3946
Fixes #3942
Modal closing animation has a weird sliding animation when the page has a scrollbar. This occurs because the scrollbar disappears/appears during modal state changes, causing layout shift that creates an unpleasant user experience.
Adding `scrollbar-gutter: auto` to the `.modal` class in `packages/daisyui/src/components/modal.css`. This property automatically manages scrollbar space reservation only when needed, preventing layout shift during modal transitions.
```css
.modal {
/* existing properties... */
scrollbar-gutter: auto; /* ← add this line */
}
```
Verified fix works across all modal types except legacy checkboxes
=> fix: modal scrollbar slide on close. closes: #3946 and #3942

packages/docs/src/components/themegenerator/Preview.svelte
displayed HEX color code is incorrect.
=> docs: theme generator

packages/daisyui/src/components/select.css
After the change of padding-inline start of .select  from ps-4 to ps-3 in 449378e93adba1fb71aba2c26515f4b9643244f9 the margin-inline-start was forgotten.
=> fix: sync margin inline start of select in label after change of padding inline start (ref #4114)

packages/daisyui/src/components/mockup.css, packages/docs/src/routes/(routes)/components/mockup-phone/+page.md
This PR refactors the mockup-phone component to be responsive and consistent across viewports and browsers.
It removes hard-coded pixel dimensions and invalid grid definitions, replacing them with scalable, ratio-based sizing while preserving the original phone silhouette, notch, and display styling.
fixed #1063 
- Added aspect-ratio: 390 / 845 for natural scaling without fixed width/height.
- Children unified via grid-area: 1 / 1 for reliable overlay stacking.
- Converted fixed px sizing (126×32px) to proportional values (32.3% × 3.8%).
- Simplified with border-radius: 9999px to always render a pill shape.
- Removed fixed 390×845px; now width: 100%; height: 100% with responsive scaling.
- Retains rounded corners (border-radius: 49px) for visual integrity.
- Ensures child <img> fills …
=> fix(mockup-phone): make layout responsive with aspect-ratio

packages/docs/src/routes/(routes)/docs/install/rails/+page.md
This PR updates the Ruby on Rails installation guide, changing the daisyUI script references to use the `.mjs` extension.
This fixes an issue for Rails developers where Tailwind CSS IntelliSense would not work in VS Code. The `.mjs` extension ensures compatibility with modern JavaScript tooling, like importmaps, used in Rails 7+.
**Related issues:**
- Fixes https://github.com/saadeghi/daisyui/discussions/4077
- Fixes https://github.com/tailwindlabs/tailwindcss-intellisense/issues/1415
=> docs(rails): Update install guide to use .mjs extension

packages/docs/src/components/Component.svelte, packages/docs/src/lib/mdsvex/remark-render-component.js
Fixes #3996
Headings in component docs were losing their markdown formatting. For example, the collapse page heading "Use Tailwind CSS `group` and `group-focus` utilities..." was showing up as plain text without the part where backticks starts around `group` and `group-focus`.
The original `getHeadingText()` function was only grabbing the first text node and ignoring everything else, rewrote it to handle all the different node types properly.
Added a `nodesToHtml()` function that converts the markdown AST nodes into actual HTML - so `inlineCode` becomes `<code>`, `emphasis` becomes `<em>`, etc. Also had to fix some quote escaping issues where href attributes were breaking because of nested quotes.
Changed the component structure to store both the plain text (for IDs) and the original …
=> fix: markdown rendering issue with backticks in component headings. closes: #3996

packages/daisyui/src/components/select.css
Fixes #4105 
> Long select options now wrap in v5.1.9. If this was an intentional design change, it should probably be documented on the Select component in the docs. Otherwise, it is a regression.
- Truncate text in `<select>`
- Changed the options container width to same width of `<select>`
- Truncate text in `<option>`
| Before | After|
| --- | --- |
| <img width="935" height="163" alt="Screenshot 2025-09-30 at 22 54 48" src="https://github.com/user-attachments/assets/e2b142e2-0d94-4bf7-9645-e704d71d2adc" /> | <img width="717" height="158" alt="Screenshot 2025-09-30 at 22 55 32" src="https://github.com/user-attachments/assets/4414538d-83d1-4c91-a9b6-a21d7f820d3d" /> |
I initially attempted to implement `text-overflow: ellipsis` to add a `...` indicator for truncated text. However, to …
=> fix(select): prevent line breaks on long text

packages/docs/src/routes/(routes)/components/table/+page.md
I noticed that the code for "Table with pinned-rows and pinned-cols" in the table documentation differs from the HTML code displayed on the page. The fixed width and height are important for the `position: sticky;` (used by `table-pin-rows` and `table-pin-cols`) to work properly.
=> docs: fix code example differs from the actual HTML code
