src/docs/components/landing/HomepageDemoBreadcrumb.vue, src/docs/components/landing/HomepageDemoButton.vue, src/docs/components/landing/HomepageDemoCard.vue, src/docs/components/landing/HomepageDemoCard2.vue, src/docs/components/landing/HomepageDemoLoading.vue, src/docs/components/landing/HomepageDemoTab.vue, src/docs/components/landing/HomepageDemoToggle.vue
fixed capitalization so it's consistent with other demo components
=> fixed typos on the landing page

src/components/unstyled/textarea.css
hi, pouya
i find a bug in textarea component. cannot change height in textarea, because defined height and min-height.
[demo]( https://codepen.io/zoghal/pen/jOBQzvo)
=> Fixed: unchangeable height in textarea

CHANGELOG.md, src/docs/pages/docs/config.vue, src/docs/pages/docs/features.vue
Thanks for the great work.
This is just a couple of typos I stumbled upon.
=> Tiny typo fixes

src/docs/components/landing/HomepageDemoNav.vue
This is an awesome tailwind plugin, everything just works and it looks amazing!
Here's a typo I saw on the landing page :)
=> Small typo fix

src/components/styled/table.css
add align-middle to the tr, td so that they become vertically aligned in middle
=> align the rows vertically center

src/components/styled/steps.css
Vertical steps can resize to content height
=> fix: #279 - Vertical steps resize to content

src/components/unstyled/modal.css
=> Make modal toggle fixed instead of absolute

src/components/styled/steps.css, src/components/unstyled/steps.css, src/docs/pages/components/steps.vue
=> feat(components): steps-horizontal 

src/docs/src/routes/components/navbar.svelte.md
=> fix: dropdown not working

package.json, src/index.js
attempt at https://github.com/saadeghi/daisyui/issues/536#issuecomment-1057615477
=> fix(config.prefix): try-catch and load prefix deps dynamically

src/docs/src/routes/components/navbar.svelte.md
Need to add tabindex="0" to label for full dropdown functionality.
=> Fix navbar dropdown bug

src/docs/src/routes/components/alert.svelte.md
Removed duplicate alert-info row in ClassTable
=> fix: duplicate alert-info

src/docs/src/translation/jp.json
=> Japanese Typo

src/docs/src/routes/components/navbar.svelte.md
=> add missing 'tabindex' attributes to navbar dropdown preview

src/docs/src/components/LangChange.svelte
The title in the language `Select` component is set to _Change Theme_ instead of _Change Language_
=> Update Language `Select` component title

src/components/unstyled/select.css
about the scroll bar, it may be ugly but i don't think it's necessary to fix it, if you want to look in more detail into it read the previous pull request i closed
=> Select with multiple attribute has now height set to auto

src/docs/src/routes/components/radio.svelte.md
Replaced Checkbox to Radio in first example
=> Update radio.svelte.md: fix Checkbox->Radio in first example

src/docs/src/components/Search.svelte, src/docs/src/components/Sidebar.svelte, src/docs/src/lib/breakpoints.js, src/docs/src/lib/mediaQuery.js, src/docs/src/routes/__layout.svelte, src/docs/svelte.config.js
Fix for #860. I saw on contribution guide that I could open a pull request directly for modifications on the documentation website. Let me know if that's okay. 
These changes simply open the sidebar by checking the relevant checkbox whenever Meta + K is used. I also added an even listener to automatically close the sidebar whenever a search result is picked. Because the sidebar is always opened on desktop by using css, these changes only affect the small screen views.
Let me know if I should change anything.
Love daisyui but this issue was driving me crazy 👍
=> [documentation site] Opening the sidebar on Meta + K

src/docs/src/routes/components/modal.svelte.md
Not sure if this was purposeful, if so sorry.
=> fix: spelling correction

src/docs/src/routes/components/bottom-navigation.svelte.md
Fix with custom colors example
=> docs(bottom-navigation): :memo: Update bottom navigation readme

src/docs/src/routes/components/carousel.svelte.md
=> Added missing words

README.md
=> Updated: readme list of components

src/docs/src/routes/components/collapse.svelte.md
Updated example code to match what is shown in the preview
=> Updated example code to match preview

src/docs/src/translation/ko.json
Edited for unity of translation.
'will be' in 234 is translated as '될 것입니다', but 'will be' in 235 is translated as '됩니다'. 
Most of the 'will be' on the current translation page has been translated as '될 것입니다'.
=> Modify translation style

src/docs/src/routes/components/avatar.svelte.md
Maybe I pay too much attention to small things 😅
=> [Docs] Correct `avatar`-`offline` class description

src/docs/src/routes/components/collapse.svelte.md, src/docs/src/routes/components/dropdown.svelte.md, src/docs/src/routes/components/menu.svelte.md, src/docs/src/routes/components/navbar.svelte.md
=> fix react tab index prop

src/components/styled/button.css
=> Don't wrap buttons

src/components/styled/button.css
=> Don't show underline for links with .btn class

src/components/styled/input.css
=> Default input text size to text-base to prevent zoom on iOS

src/docs/src/routes/components/modal.svelte.md
Replace unsupported HTML comments with react comments in the modal page
=> docs: Error from comments in modal react examples

src/components/styled/modal.css
- closing https://github.com/saadeghi/daisyui/issues/436
- based on: https://fvsch.com/articles/transition-fade/test5.html
=> fix(modal): add smooth closing transition

src/components/styled/collapse.css, src/components/unstyled/collapse.css
I made the change, it works well.
=> fix: #1426 collapse uses focus-within instead of focus

src/docs/src/translation/pt.json
=> Adjust translation

src/docs/src/routes/components/modal.svelte.md
In Modal using anchor link section fix `Put this part before </body> tag` comment section
=> Modal using anchor link - Add comment for JSX

src/components/styled/tab.css
Just a tab-disabled, as with other controls.  Sometimes you just need to disable a tab.
=> tab-disabled

src/components/styled/breadcrumbs.css, src/components/unstyled/breadcrumbs.css
breadcrumb should support an ordered list (SEO)
#1569 
Reproduction of the issue: https://play.tailwindcss.com/lWnURBWN1C
=> fix: #1569 breadcrumb should support an ordered list (SEO)

src/docs/src/translation/ru.json
I think `Responsive` means that components and anything else adapt to different devices. In the Russian community, we call it `Отзывчивый дизайн` or `Адаптивный дизайн` (Responsive design or Adaptive design)
=> `Респонсивный` -> `Отзывчивый`

src/colors/functions.js
Oops, sorry for the mess, `git rebase` hates me 🤣
=> refactor color functions

src/docs/src/routes/components/button.svelte.md
Make medium size explicitly documented in the button sizes section. 
Resolves https://github.com/saadeghi/daisyui/issues/1837
=> chore(docs): Update button.svelte.md

src/components/styled/button.css
=> fix: btn no-animation size change on click

src/docs/src/lib/data.js
Congratulations on daisyui 3.0.0 release🎉.
issue[https://github.com/saadeghi/daisyui/issues/1872](https://github.com/saadeghi/daisyui/issues/1872)
fix budge value in Modal
=> make initials lowercased

README.md
Added a new starter to the list, Nuxtwind Daisy, which is a Nuxt 3 starter with pre-installed configurations like fonts, icons, animations, etc. It uses Tailwind CSS and daisyUI Template.
=> 🆕 feat(README.md): add Nuxtwind Daisy starter to the list

src/components/styled/file-input.css, src/components/styled/input.css
=> fix: focus outline proper opacity

src/docs/src/routes/docs/layout-and-typography/+page.svelte.md, src/docs/src/translation/en.json, src/docs/src/translation/es.json, src/docs/src/translation/fr.json, src/docs/src/translation/id.json, src/docs/src/translation/jp.json, src/docs/src/translation/ko.json, src/docs/src/translation/pt.json, src/docs/src/translation/ru.json, src/docs/src/translation/zh_cn.json, src/docs/src/translation/zh_tw.json
https://daisyui.com/docs/layout-and-typography/#-1
There's a missing fullstop, which causes the sentence to come off oddly. 
It looks like the translation files need to be updated to support this PR, I'll get on that.
The index page is looking pretty slick, good work on the site and the project #:pray:
=> fix(layout_typography): Grammatical Error, missing period

src/docs/src/routes/components/bottom-navigation/+page.svelte.md
https://daisyui.com/components/bottom-navigation/#with-custom-colors
```jsx
<div className="btm-nav">
<button className="bg-pink-200 text-pink-600">
<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" /></svg>
<span className="btm-nav-label">Home</span>
</button>
<button className="active bg-neutral text-neutral-content">
<svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 …
```
=> docs(btm-nav): Mismatch preview and html

src/docs/src/routes/docs/config/+page.svelte.md
This wasn't updated along with [3.0 release](https://daisyui.com/docs/changelog/#theme-improvements).
=> docs: fix default value of theme config

src/docs/src/routes/components/accordion/+page.svelte.md, src/docs/src/translation/id.json
Update Indonesia translation due to components update
=> docs: update id.json and accordion examples to be able to support translation

src/components/styled/input.css
As discussed here
https://github.com/saadeghi/daisyui/discussions/2350
=> feat: add `:focus-within` style to `.input`

src/components/unstyled/join.css
as described here: https://github.com/saadeghi/daisyui/issues/2408
tested in Chrome and Safari in macOS
=> no round nested join items

src/docs/src/routes/(docs)/components/theme-controller/+page.svelte.md
Hi! 
Noticed some typos in Theme Controller page and took a courtesy to fix em :)
=> Fixed some typos in Theme Controller page

src/docs/src/routes/(docs)/components/divider/+page.svelte.md
Remove flex-col class as it is a horizontal divider.
=> docs: update html for divider (horizontal)

src/docs/src/routes/(docs)/docs/utilities/+page.svelte.md
Updated page title and code examples for border radius.
=> Update readme for utilities

src/components/styled/tab.css
=> fix: #2573 tab styles

src/docs/static/logos/angular.svg
update logo to use the latest one based on the Angular's press kit
https://angular.dev/press-kit#press-and-media
=> Update Angular logo

src/docs/static/logos/angular.svg
Apologies I messed up the width and height of the logo in previous PR
=> Update angular logo svg width and height

src/base/postcss.config.js, src/base/tailwind.config.js
Transform theme colors in the base colors configuration.
Resolves #2634
=> fix: #2634 compile base colors

src/docs/src/routes/(docs)/components/radial-progress/+page.svelte.md
[Here](https://github.com/saadeghi/daisyui/blob/master/src/components/styled/radial-progress.css) you find the configured default.
=> Fix docs about default size of Radial Progress

src/docs/src/routes/(docs)/components/modal/+page.svelte.md
"there is a" instead of "there a"
=> Fix small typo

.github/CONTRIBUTING.md
This PR adds a "Contribute translations" section to the CONTRIBUTING.md.
**Content:**
- link to inlang localization editor
- link to "how to use" guide
- badge with current translation status
**Preview badge:**
[![inlang status badge](https://badge.inlang.com/?url=github.com/saadeghi/daisyui&project=/src/docs/project.inlang)](https://fink.inlang.com/github.com/saadeghi/daisyui?ref=badge)
This will help contributors discover and use the Fink localization editor to add missing translations or fix typos.
=> Add "Contribute translations" to CONTRIBUTING.md

src/docs/src/translation/ja.json, src/docs/src/translation/zh_hans.json
Fixes: https://github.com/saadeghi/daisyui/issues/2897
=> fix: fix typo taiwind -> tailwind

src/components/styled/select.css, src/components/styled/textarea.css
=> fix: consistent disabled form inputs

src/docs/src/routes/(docs)/theme-generator/+page.svelte
Added a button to show all colors in the theme generator.
With the switch off:
With the switch on:
=> Docs: Update theme generator

src/components/styled/checkbox.css
Added border-0 to the disabled state of the checkbox to fix the issue highlighted here: https://github.com/saadeghi/daisyui/issues/3009
=> Fix for #3009

src/docs/src/routes/(docs)/docs/themes/+page.svelte.md
I am just providing the instructions as read in #640 
I just wanted to be able to apply dark: selector to increase the border in light mode, and #640 was the solution which I think others would be looking for
=> Instruction to applying dark selector

src/theming/themes.d.ts
This PR fixes the incorrect type declaration identified in #3034
=> fix: #3034 incorrect theme type declaration

src/docs/src/routes/(docs)/theme-generator/+page.svelte
This PR fixes issue #3092 and #2645 .
=> fix:#3092 and #2645 theme generator issues

src/docs/src/routes/(docs)/components/footer/+page.svx
removed $ from {new Date.getFullYear()} in jsx examples as its not needed
=> Fixed footer example jsx code for getFullYear

src/docs/src/routes/(docs)/components/divider/+page.svx
=> Update Divider html example #3151

src/docs/src/routes/(docs)/components/input/+page.svx
=> Fixed typo in documentation

src/docs/src/routes/(docs)/docs/themes/+page.svx
Minor change to correctly express the intended message.
=> Clarify wording for selecting themes to include

packages/daisyui/build.js, packages/daisyui/functions/compileAndExtractStyles.js, packages/daisyui/functions/contrast.test.js, packages/daisyui/functions/cssToJs.js, packages/daisyui/functions/extractClasses.js, packages/daisyui/functions/extractClasses.test.js, packages/daisyui/functions/filesExist.test.js, packages/daisyui/functions/generateChunks.js, packages/daisyui/functions/generateColorRules.js, packages/daisyui/functions/generateImports.js, packages/daisyui/functions/generateRawStyles.js, packages/daisyui/functions/generateThemeFiles.js, packages/daisyui/functions/generateThemes.js, packages/daisyui/functions/generateThemesObject.js, packages/daisyui/functions/packCss.js, packages/daisyui/functions/themes.test.js, packages/daisyui/functions/validatecss.test.js, packages/daisyui/index.js
Support plain esm loading, e.g. via https://esm.sh/, replacing at least
* import.meta.dir -> import.meta.dirname
* folder imports with "/index.js" suffix
I'd like to preview compatibility with unocss directly in [unocss playground](https://unocss.dev/play/#html=DwEwlgbgBAxgNgQwM5ILwCIC2CAeBaAdzyRgCcBTcgOz0xCk3wQFcAXAeygAc8AWdAHwAoKFFCRYiFBgBmccjihhW5TEjwxqK0oJGixACwCMk5GnQqcrPAFYccKDPZVrAZgAM7hqT6CAqlTsAMIAyiFQANRQIAhgSACefgCSwAD0xsL6YghQBhQyGAasrFxIAFypqQDmygbMAEYAdDDsmKkImORgVAYIpCCsqcyBMCh4XBRI5NYxcfG6WaLi0PBmGGB47DCsYC002KQA1ng1rHX1eEYAbFCWbva57BDkpGXsXAgwyvG27oJp4AgmX0aQQwIBkGEemABgATKZpFgfvC7nhXPZBABBbZgZxINJwqFLAyuBHmJwuPD1dhweiYH4mVEYgQAITYHCoBNc4MBZIw9L4UCQH00eB%2B-GBS0BkpBBl4fPQFOs1NpgjZxTxUAItSg9VICCo9BacHYpHx6V4MqW9XZzgV9VYVDVts5qRtGqoVrE7o59sdusdeCo5DY%2BrgggAciHWGG0j7nF7gPGqH …
=> fix: node/esm compatibility

packages/docs/src/routes/(routes)/components/hero/+page.md
Noticed a typo in the doc just fixed it, not sure about the process happy to create an issue if needed
=> Fix typo of missing closing tag in a div

packages/daisyui/src/components/chat.css
=> fix: #3389 - Change cascade order of .chat-bubble class

packages/docs/src/routes/(routes)/docs/config/+page.md
This one updates
`https://github.com/saadeghi/daisyui/tree/master/packages/daisyui/src`
to
`https://github.com/saadeghi/daisyui/tree/v5/packages/daisyui/src/components`
=> Update link in docs

packages/docs/src/translation/ja.json
Describe the changes you have conducted here
Preview the messages on https://inlang.com/github.com/yoshi6jp/daisyui .
=> Update translations ja

packages/docs/src/routes/(routes)/docs/themes/+page.md
@variant for dark is not supported by newest tailwindcss plugin.
=> Update dark variant

packages/docs/src/routes/(routes)/components/footer/+page.md
=> docs: fixed footer responsive issue on mobile screen

packages/docs/src/routes/(routes)/components/fieldset/+page.md
Found in #3471 
No clue if it would be better to add it to the `Join` documentation rather than to the `Fieldset` documentation...
=> Add example for using fieldset with join items

packages/docs/src/routes/(routes)/components/dropdown/+page.md
Component docs says `--acnhor-1`, should be `--anchor-1`
=> Fix typo in dropdown component docs

packages/daisyui/src/components/label.css, packages/docs/src/routes/(routes)/components/label/+page.md
=> Allow for a placeholder when using floating labels

.prettierignore
Fixes #3542
But also the prettier setup of the repo in general.
=> Add .prettierignore

packages/docs/src/routes/(routes)/components/collapse/+page.md
=> Duplicate classes

packages/docs/src/routes/(routes)/docs/install/laravel/+page.md
=> update laravel docs

packages/docs/src/routes/(routes)/docs/intro/+page.md
=> Fixing typos

packages/docs/src/routes/(routes)/docs/install/rails/+page.md, packages/docs/src/routes/(routes)/docs/install/standalone/+page.md, packages/docs/src/routes/(routes)/docs/intro/+page.md, packages/docs/src/routes/(routes)/docs/v5/+page.md
=> fix(docs): fix typos

packages/docs/src/components/Component.svelte
=> Fix: Updating the copy icon on clipboard to take the updated prefix value

packages/daisyui/src/components/tab.css
=> fix: tab-content overflows when tabs has height. closes: #3843

packages/docs/src/routes/(routes)/components/stat/+page.md
Fixed the usage of a non-existing class name.
=> fix: correct typo in class name

packages/docs/src/routes/(routes)/docs/editor/zed/+page.md
Fixes two minor issues with the Zed documentation.
_By the way, thank you for having docs for my favorite editor!_
=> Improve Zed docs
